### ISSUE TITLE
Resizing does not wrap text correctly

### ISSUE THREAD

**Issue by JestDotty** [amejia1/atom-xterm#10]
example:
![image](https://user-images.githubusercontent.com/4729968/33686086-a9729e1c-daa1-11e7-9d2e-dae91e5db5fe.png)

reproduction:
1. output some stuff in console
2. reduce width of console until it cuts off (does not wrap. Should it wrap?)
3. increase width of console
= text is cutoff

**Comment by amejia1** [comment]
I think this may be a problem due to the xterm.js library. Their v3 library seems to fix a lot of issues but it hasn't been released yet.

**Comment by amejia1** [comment]
Double checked and indeed this is an issue with xterm.js. This has yet to be fixed (see https://github.com/xtermjs/xterm.js/issues/166).
