### ISSUE TITLE
[feature request] support for Bash on Ubuntu on Windows (WSL)

### ISSUE THREAD

**Issue by francescoboc** [amejia1/atom-xterm#12]
Woud it be possible to load a Bash on Ubuntu on Windows terminal? (WSL)

Thanks,
F.

**Comment by UziTech** [comment]
you should be able to just type `bash` in the terminal to open WSL on Windows 10

**Comment by amejia1** [comment]
It's possible to do this already, just use `bash.exe` as the command to run. You could also use the full path `C:\Windows\System32\bash.exe`. I found some slight issue with Bash on Ubuntu on Windows when using node-pty (what atom-xterm uses) so you might find it better to use the bash command from Git for Windows.
