### ISSUE TITLE
Custom theme and fonts for xterm

### ISSUE THREAD

**Issue by atgiovannini** [amejia1/atom-xterm#28]
I like a lot this plugin for atom, but I can't change font-family. ¿Can implement customize fonts?

Also when changing font size in xterm settings, shell fonts don't change.
It would be a nice feature to support different shell styles.

**Comment by amejia1** [comment]
Changing font size should at least be supported and it was with xterm.js v2. I'll look into what is needed to reenable this in xterm.js v3.

**Comment by amejia1** [comment]
I have the font size issue completely fixed and pending release.

Custom theme will come next. It will be made possible through xterm.js own Terminal [options](https://github.com/xtermjs/xterm.js/blob/3.0.2/typings/xterm.d.ts#L14).
