### ISSUE TITLE
Font does not use the setting in atom-xterm config.

### ISSUE THREAD

**Issue by magler** [amejia1/atom-xterm#29]
When I open a tab, the font size continues to use the default, even if it is changed in the settings. I currently have the font set to 8 for atom-xterm, and 9 for atom editor. font in xterm is using what looks like size 14.

Running: atom-xterm 5.1.0

System Version: OS X 10.11.6

**Comment by amejia1** [comment]
The switch to xterm.js v3 broke this. I'll have to see what I need to do to get this fixed.

**Comment by JestDotty** [comment]
in a similar vein I used custom styles.less to set the font-family on xterm but it broke with the update. Seems xterm is now using canvas for the text and css no longer applies? Or maybe I'm doing something wrong.

**Comment by amejia1** [comment]
@magler The font size issue is completely fixed. Now whenever you update the font size, it should update all currently opened terminals as well as future terminals.

@JestDotty See https://github.com/amejia1/atom-xterm/issues/28 .
