### ISSUE TITLE
Question: how to disable pinch zoom gesture?

### ISSUE THREAD

**Issue by deepsweet** [amejia1/atom-xterm#39]
I found it very annoying that I can change font size with pinch gesture, is there a way to disable it? Can't find appropriate options in xterm.js.

**Comment by deepsweet** [comment]
macOS, and that's exactly how pinch gesture works, see https://bugzilla.mozilla.org/show_bug.cgi?id=1052253 as an example.

**Comment by deepsweet** [comment]
could you please add an option to disable "ctrl + mousewheel" feature?

**Comment by amejia1** [comment]
Noting here that the pinch to zoom mapping to ctrl+mousewheel is a feature in chrome and firefox 55+ for certain, doesn't matter what OS. See also https://developer.mozilla.org/en-US/docs/Web/Events/wheel
