### ISSUE TITLE
Use node-pty-prebuilt for now

### ISSUE THREAD

**Issue by HotelCalifornia** [amejia1/atom-xterm#60]
Per https://github.com/Microsoft/node-pty/issues/46#issuecomment-386624832 and the linked PR, node-pty is going to hold off on publishing prebuilt binaries for the time being.

Is there a problem with switching dependencies from node-pty to node-pty-prebuilt until this happens?

**Comment by amejia1** [comment]
The latest releases should already be using node-pty-prebuilt. It has been used for a while. See also [this commit](https://github.com/amejia1/atom-xterm/blob/v6.5.0/package.json#L46).
