### ISSUE TITLE
How to set font?

### ISSUE THREAD

**Issue by austinbutler** [amejia1/atom-xterm#8]
Currently it seems the font does not match the Atom editor font nor the system mono font set. Is there a way to set it? Or, alternatively, could it inherit the editor's font in Atom?

**Comment by amejia1** [comment]
It should be using the system mono font. See also [here](https://github.com/xtermjs/xterm.js/blob/2.9.2/dist/xterm.css#L41).

Can you show an image of what you see?

**Comment by austinbutler** [comment]
Hmm did some more testing and everything seems to work great on Linux. On OS X though it's ugly and the cursor doesn't behave properly. Maybe that is just the system font? I think I meant the font from Terminal on OS X, not sure how to discern the system mono font on OSX.

Terminal prompt:
![image](https://user-images.githubusercontent.com/354741/34457903-763193d8-ed74-11e7-9308-c42b9f6d3478.png)

Terminal with command, showing text starting at the wrong place:
![image](https://user-images.githubusercontent.com/354741/34457912-bea06f36-ed74-11e7-825d-1dd27c40f182.png)

Terminal in Linux with cursor after the dollar sign (correct):
![image](https://user-images.githubusercontent.com/354741/34457919-0a26dc1a-ed75-11e7-9af2-8fa8daad7585.png)

**Comment by austinbutler** [comment]
OK I edited the font-family in xterm.css and that took the font I want ("Source Code Pro") and also fixed the cursor issue.

**Comment by amejia1** [comment]
I'm going to need some help with this then since I don't own a macos system. I did some testing before with help from my fellow mac users and the last release worked fine for them so I don't want to change anything just yet.

**Comment by austinbutler** [comment]
If you need me to test let me know. You could also use Vagrant for testing: https://github.com/AndrewDryga/vagrant-box-osx

**Comment by amejia1** [comment]
I have since switched to xterm.js v3 and from what I seen and heard from the macOS users I know, atom-xterm just works for them. For the 6.0.0 release of atom-xterm, I have enabled the option for users to choose any of the available options for the xterm.js Terminal class. That includes the font family (see [here](https://github.com/xtermjs/xterm.js/blob/3.0.2/typings/xterm.d.ts#L58)).

**Comment by yumitsu** [comment]
@amejia1 I tried to pass `{'fontFamily': 'Menlo Nerd Font'}` as xterm.js options, but font doesn't seems to be changed.
